### ISSUE TITLE
volumes_slice.qmd

### ISSUE THREAD

**Issue by fangliu-tju** [jverzani/CalculusWithJuliaNotes.jl#102]
I can not catch the meaning of this equation, it seems not correct.
![image](https://github.com/jverzani/CalculusWithJuliaNotes.jl/assets/46347645/286e21e1-e833-4e0a-8a63-c7ea64d92d69)

And in this question, the range of $x$ is in [0,log(2)] or (-Inf,log(2)]?
![image](https://github.com/jverzani/CalculusWithJuliaNotes.jl/assets/46347645/ab58a5da-77e3-4dd4-8026-d21f27362285)

**Comment by jverzani** [comment]
Yes, thanks. I don't know what I was thinking on that first one. It is just wrong. Thanks.

As for the second, the "first quadrant" part is supposed to indicate `x >= 0`. I'll make it more explicit and add a figure.
