### ISSUE TITLE
Output not showing

### ISSUE THREAD

**Issue by mtila** [jverzani/CalculusWithJuliaNotes.jl#120]
For #51, the outputs do not display.

**Comment by jverzani** [comment]
THanks, can you tell me where you are looking? I checked the first one (a limit) and it is showing up here: https://jverzani.github.io/CalculusWithJuliaNotes.jl/limits/limits.html#question-16

**Comment by mtila** [comment]
I'm looking at #51 the differential equations suite and getting:

LoadError: ArgumentError: Package OrdinaryDiffEq not found in current path.
- Run `import Pkg; Pkg.add("OrdinaryDiffEq")` to install the
OrdinaryDiffEq package.

**Comment by jverzani** [comment]
Ahh, thanks! I'll have a look.

**Comment by jverzani** [comment]
Many thanks! Should be fixed now: https://jverzani.github.io/CalculusWithJuliaNotes.jl/ODEs/differential_equations.html
