### ISSUE TITLE
The question on Cauchy's bound with coefficients 1, 2, 3, 4 gives an error

### ISSUE THREAD

**Issue by Sebastiaan-Jans** [jverzani/CalculusWithJuliaNotes.jl#121]
Instead of an answer prompt, there's:
`LoadError: PyError ($(Expr(:escape, :(ccall(#= /Users/verzani/.julia/packages/PyCall/1gn3u/src/pyfncall.jl:43 =# @pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, pyargsptr, kw))))) <class 'AttributeError'>
AttributeError("'Float' object has no attribute 'array_form'")
  File "/Users/verzani/.julia/conda/3/lib/python3.7/site-packages/sympy/combinatorics/permutations.py", line 1372, in __mul__
    b = other.array_form`

**Comment by jverzani** [comment]
Thank you for reporting this! I'll have a look and see what broke.
