### ISSUE TITLE
12.1.3 `solveset` does not return a FiniteSet

### ISSUE THREAD

**Issue by Sebastiaan-Jans** [jverzani/CalculusWithJuliaNotes.jl#122]
At least for me, on Julia 1.10, solveset in fact just returns a normal Julia Set, on which `elements` is not defined.

**Comment by jverzani** [comment]
Yes, thanks. This changed with `SymPy` rolled over to v2.0. I'll have to update these notes to reflect that. Very much appreciate your report!

**Comment by jverzani** [comment]
This should be fixed now. Thanks again!

**Comment by Sebastiaan-Jans** [comment]
Thanks for the quick fix, and for the notes in general! As a small note, it isn't actually necessary to do an intermediate `collect` here, as you seem to suggest in your fix (though not explicitly). `N.(collect(solveset(p)))` could also just be `N.(solveset(p))`. `collect`ing it does perhaps fit better with the mainly vector-focused approach of the notes; it's a bit more explicit. I'm not saying there's anything wrong with how it is, I just thought I'd mention it.

**Comment by jverzani** [comment]
Yes, I actually tried that and was a bit surprised that broadcasting over a set returns a vector (whereas mapping returns an error). I thought about writing it the way you have but thought it would need a comment. Let me do that instead. 

Thanks again!
