### ISSUE TITLE
Cannot download the PDF of the book

### ISSUE THREAD

**Issue by ritog** [jverzani/CalculusWithJuliaNotes.jl#124]
I wanted to download the PDF version of the book, but I got a 404 error.

![image](https://github.com/jverzani/CalculusWithJuliaNotes.jl/assets/58001482/a7d5e469-e8ba-4d53-8b58-a7f7f1659cbc)

I wanted to download the PDF from the top right corner of the homepage of the book.

![image](https://github.com/jverzani/CalculusWithJuliaNotes.jl/assets/58001482/afaf5e39-21a2-4d3f-a230-6bdf3f67dca0)

Please make the PDF available, as I would love to download the book in PDF format and read it offline.

**Comment by jverzani** [comment]
Sorry, I tried and had no luck creating the pdf from the files. There are parts within that are HTML specific and decoupling proved to be too much work. If there are other avenues you can think of, do let me know.
