### ISSUE TITLE
Suggestion for first figure in 25.4

### ISSUE THREAD

**Issue by ngiann** [jverzani/CalculusWithJuliaNotes.jl#131]
It may be useful to show the points a,b and c in the first figure of 25.4 (even though the mean value theorem does not help us find c but only assures us of its existence).

**Comment by hex4lcodes** [comment]
Hi, the binder notebook returns an unknown image error. Could you please fix?

**Comment by jverzani** [comment]
Thanks, I added two new links and directions to use colab. 

I modified this page: https://jverzani.github.io/CalculusWithJuliaNotes.jl/precalc/julia_overview.html

If you found the binder links elsewhere or have thoughts on where they should be, let me know.
