### ISSUE TITLE
NOT NECESSARILY A ISSUE ON YOUR END

### ISSUE THREAD

**Issue by hex4lcodes** [jverzani/CalculusWithJuliaNotes.jl#133]
Hi, sorry to bother you again, Im having issues with questions 4 and 5 for the calculator lesson, the program gives me one answer, but the correct one is completely different could you possibly look at my code and advise me what I could be doing wrong?

Here is number 4s:

selma = 9-5*(3-4)/6-2

print(selma)

I dont know the proper way to format number 5. :((

**Comment by jverzani** [comment]
That long bar implies grouping, so you need parentheses in the denomator:

```
 9 - 5*(3-4)/(6-2)
```

**Comment by jverzani** [comment]
Oops, *and* the numerator `(9 - 5*(3-4)) / (6-2)`

**Comment by hex4lcodes** [comment]
disregard the question about the top one with the decimals. still have questions about that bottom one if you dont mind

**Comment by hex4lcodes** [comment]
thank you! 💯
