### ISSUE TITLE
pdf button did not work for me

### ISSUE THREAD

**Issue by psteffensen** [jverzani/CalculusWithJuliaNotes.jl#135]
It could not find the pdf file when I pressed the pdf button.

Amazing site you have made, by the way!

**Comment by psteffensen** [comment]
I just found this comment:

**Comment by jverzani** [comment]
And that might be a bit optimistic. It worked once, but last time I tried something timed out. If you are really interested and can't make it work, let me know. I would like to see if the relatively new `typst` can be used to create pdfs.

**Comment by jverzani** [comment]
In case you tried playing along at home, the typst idea gets stopped dead in the water, as quarto does not have support for typst and book projects. I'm looking at generating a pdf. Finger crossed.

**Comment by jverzani** [comment]
Oh well, no luck. It seems it would be a heavy lift to create pdfs with quarto right now. Sorry.

**Comment by jverzani** [comment]
I made a pdf. It isn't perfect, but maybe will be sufficient. 

Try: https://www.dropbox.com/scl/fi/vv8ee9a5xb9qbsw87f3bl/CalculusWithJulia.pdf?rlkey=u7ambk19sowelxtgiaosjozzo&st=i0hxwx29&dl=0

I had to stitch things together, so there is not table of contents or index for navigation.

**Comment by psteffensen** [comment]
Thank you! I have downloaded it now.

I tried generate it myself. I clone the repository and tried to generate
with Quarto, but it was on my work computer and security messed it up.

Den tis 15 okt. 2024 03:13john verzani ***@***.***> skrev:
