### ISSUE TITLE
I found there are more contents in "functions.html" than in "functions.qmd"

### ISSUE THREAD

**Issue by fangliu-tju** [jverzani/CalculusWithJuliaNotes.jl#50]
I found some errors in the chapter of Functions, but I can not find corresponding things in functions.qmd, such as "twotox" functions. Am I gone the wrong place?

**Comment by jverzani** [comment]
Hmm, let me look that one just got added recently, so I might need to push the changes.

**Comment by jverzani** [comment]
Yup, that was it. Sorry. (As CI can't handle this size project without timing out, I have to remember to both push  the qmd changes and the html changes.)

**Comment by TS-CUBED** [comment]
> As CI can't handle this size project without timing out

Oh, that's disappointing. Wanted to set up something similar and had hoped to have CI deal with it. But will render locally then.

BTW, I hope you don't mind if I point my students to this from my lecture slides?

**Comment by jverzani** [comment]
We have a smaller set of notes here: https://github.com/mth229/mth229.github.io Those use the CI to build the notes. Maybe that is helpful.

And, sure, I'd be very happy to have you point to these notes.
