### ISSUE TITLE
Wrong numbers of ants weight

### ISSUE THREAD

**Issue by appomsk** [jverzani/CalculusWithJuliaNotes.jl#52]
They definitly used the metric megatons and dry carbon weight of the ants rather than the ants themselves. Source - https://www.pnas.org/doi/abs/10.1073/pnas.2201550119

**Comment by jverzani** [comment]
Thanks, I have some errors in that example, for sure! (I even blew the conversion of pounds to grams). I'll fix that and convert metric tons to 2000 lb tons.

**Comment by jverzani** [comment]
This should be fixed now: https://jverzani.github.io/CalculusWithJuliaNotes.jl/precalc/calculator.html#example-5

Thanks for the feedback!
