### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by EnckyOff** [jverzani/CalculusWithJuliaNotes.jl#53]
The link  to julia interfaces at main page is wrong (https://jverzani.github.io/CalculusWithJuliaNotes.jl/.misc/julia_interfaces.html)

**Comment by jverzani** [comment]
Thanks. There is a "." before misc that slipped in somehow.

**Comment by jverzani** [comment]
All fixed now. Thanks for taking the time to mention this.
