### ISSUE TITLE
quarto/integrals/mean_value_theorem.qmd

### ISSUE THREAD

**Issue by fangliu-tju** [jverzani/CalculusWithJuliaNotes.jl#98]
In the "quarto/integrals/mean_value_theorem.qmd", the third question, It seems no answer is correct.

![image](https://github.com/jverzani/CalculusWithJuliaNotes.jl/assets/46347645/037fb2c3-7aa6-4d23-9959-f3ebf923b796)

**Comment by jverzani** [comment]
Yes, there is something amiss, the integral should be ``int_0^t (v0 + as) ds``. Thanks for pointing this oujt
